apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai.fullname" . }}
  labels:
  {{- include "yatai.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    server:  # the server config section
      enable_https: false  # if the yatai is deployed as an https server, set it to ture
      port: 7777  # the server port
      session_secret_key: {{ include "yatai.sessionSecretKey" . }}  # the cookie secret, must modify and persist it when deployed to the production environment
      migration_dir: /app/db/migrations  # the migrations sql files directory

    postgresql:  # the database config section
      host: {{ .Values.infra.postgresql.host }}
      port: {{ .Values.infra.postgresql.port }}
      user: {{ .Values.infra.postgresql.user }}
      password: {{ .Values.infra.postgresql.password }}
      database: {{ .Values.infra.postgresql.database }}

    oauth:
      github:  # https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app
        client_id: {{ .Values.oauth.github.client_id }}
        client_secret: {{ .Values.oauth.github.client_secret }}
